var five = 5;
var ten = 10;
// console.log("test 1 : five is equal to five?");
// console.log(five == 5);
// console.log( "test 2 :  five is equal to ten");
// console.log(five == 10);
// console.log("test 3 : five  greaterthen six ");
// console.log(five > 6);
// console.log("test 4 : five is lessthen six");
// console.log(five < 6);
console.log((5 > 2) && (5 < 3));
console.log((2 < 5) || (3 < 5));
console.log(!(5 > 2));
